### ISSUE TITLE
AID crashed and quit

### ISSUE THREAD

**Issue by freemedom** [maikherbig/AIDeveloper#50]
When I clicked "Start fitting", it showed this interface
![1PE %5K7E2VE13I%{U0BN@P](https://user-images.githubusercontent.com/57294686/158059335-d13a3b21-a564-4687-ab91-fc29ff710b44.png)
cmd window showed 
![`3))JI_NON9AK71YGXHZIU1](https://user-images.githubusercontent.com/57294686/158059353-c9d7d941-bc19-41bc-b9b5-6774aa139ec9.png)
, and about ten seconds later, the AID crashed and quit.
I don't know what went wrong? Maybe there's something wrong with the image files? Thanks.

**Comment by maikherbig** [comment]
Thanks for reporting!
I looks like you want to train some of the "pretrained models". Most of them require image dimensions larger than 32x32pix. Could you please do all the settings again in the AIDeveloper user interface and just before you would click on "Initialize/Fit Model" please click on instead on File->Save session. That will create an Excel file containing all parameters that you want to use. If you send this file to me, I could try and reproduce and solve the error.
Thanks in advance

**Comment by freemedom** [comment]
https://1drv.ms/x/s!At8uH42USKmhePKQgsyGjW5Gu7c?e=369Jmv
This is the Excel.Thanks.

**Comment by freemedom** [comment]
After I clicked  "Save Session", this came up.
![image](https://user-images.githubusercontent.com/57294686/158098915-f45e3fea-e6fe-4fee-a62c-113e52013070.png)

**Comment by maikherbig** [comment]
From the Excel file, I can see that you are basically using default settings and a simple CNN architecture. I don't see why that should not work. Would you please be so kind and also send the data that has been used (I have tried it with my own data and I could not reproduce the error)?
For now, you could try the [older version of AIDeveloper (v.0.2.3)](https://github.com/maikherbig/AIDeveloper/releases/tag/0.2.0). This version was tested for a long time and is very likely to work. Please let me know if it works, or not. That could help me to find the issue in v0.3.0.

Please note that v0.3.0 was developed to update dependencies (updated Python, TensorFlow etc.) which resulted in various breaks of the code. Such bugs as you are experiencing, are annoying but really hard to find sometimes. Hence, I'm really grateful for your feedback!

**Comment by maikherbig** [comment]
The issue you highlighted above (get_metrics() takes 1 positional argument....)https://github.com/maikherbig/AIDeveloper/issues/50#issuecomment-1066300121 is now solved via: [c396a6f](https://github.com/maikherbig/AIDeveloper/commit/c396a6fa1e5ff46748b3e9702517a0a041dc593d)

**Comment by freemedom** [comment]
I downloaded and tested version 0.2.0, and it worked fine.

**Comment by freemedom** [comment]
This is four rtdc files.Thanks.
https://1drv.ms/u/s!At8uH42USKmhfZrP5TOQvg_mieE?e=7ifqrN

**Comment by maikherbig** [comment]
Hmm that's a suboptimal solution. Another user has reported a similar problem and installing
Visual C++ (required by TensorFlow) was the solution [LINK](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) . You would most likely need the x64 version: [download link](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by freemedom** [comment]
I just installed this library, but unfortunately 0.3.0 still crashed and exited.
![image](https://user-images.githubusercontent.com/57294686/158776208-f25bfb45-e10e-432b-8d0f-75477393a04b.png)

**Comment by maikherbig** [comment]
Sorry for the delay.
I now had time to have a look at your data. Unfortunately, I cannot reproduce the error. Model training goes very well (99% validation acc.)
Hence, the issue must be the system. You can find out why it crashes by starting AIDeveloper using the command prompt:
- click the search bar next to the windows logo and type "cmd"
- open the "command prompt"
- change the directory to the path, where the "AIDeveloper_0.3.0.exe" is located
- type "AIDeveloper_0.3.0.exe" into the cmd terminal to start the software.
- now AIDeveloper should still crash, but you can see the error message in the terminal.
- It would be great if you could send a screenshot of the error message!

**Comment by freemedom** [comment]
Thank you very much. I will try to solve it after my holiday.
